version: "3.2"

services:
  php:
    image: wodby/php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_PHAR_READONLY: $PHP_PHAR_READONLY
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
